"""empty message

Revision ID: 18b1aecde3a5
Revises: 356308eb199b
Create Date: 2021-09-30 11:18:39.473481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b1aecde3a5'
down_revision = '356308eb199b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'parent_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_pic', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
