"""empty message

Revision ID: 356308eb199b
Revises: 808bc3d090c7
Create Date: 2021-09-30 09:50:57.810124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '356308eb199b'
down_revision = '808bc3d090c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('bookings', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.add_column('events', sa.Column('duration', sa.Integer(), nullable=False))
    op.alter_column('events', 'event_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'how_many_kids',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('events', 'cost',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'body',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('users', 'parent_pic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'parent_pic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reviews', 'body',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('events', 'cost',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('events', 'how_many_kids',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'event_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('events', 'duration')
    op.alter_column('bookings', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('bookings', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
