"""empty message

Revision ID: 808bc3d090c7
Revises: 00c60bcd6359
Create Date: 2021-09-23 09:58:59.562332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808bc3d090c7'
down_revision = '00c60bcd6359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=25), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
